name: deploy_to_firebase_hosting

on:
  push:
    branches:
      - master
    tags:
      - release-production-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build page
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy_to_firebase:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build
        uses: actions/download-artifact@master
        with: 
          name: build
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN }