name: deploy_to_firebase_hosting

on:
  push:
    branches:
      - master
    tags:
      - release-production-*

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build page
        run: npm run build

      - name: Checkout the repository
        uses: actions/checkout@master
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
          publish_dir: ./build
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}